[
  "Jamelia Waller, 1",
  "Gracie-Leigh Mccallum, 3",
  "Margot Mckay, 5",
  "Jodie Dyer, 6",
  "Ffion Firth, 8",
  "Billie-Jo Dunlap, 9",
  "Sachin Chan, 10",
  "Una Beach, 11",
  "Bluebell Robles, 12",
  "Nur Combs, 13",
  "Vincenzo Conner, 14",
  "Maddy Novak, 16",
  "Kodi Collier, 17",
  "Vladimir Vasov, 18",
  "Butterfree Crackersprout, 19",
  "Oscarbait Crackersprout, 20",
  "Bendydick Chickenstrips, 21",
  "Rada Ilieva, 24",
  "Bombadil Rivendell, 25",
  "Francisco Fleming, 27",
  "Romy Harrison, 28",
  "Bunsenburner Crumplehorn, 30",
  "Patience Lyon, 39",
];
